---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---

---{r}
library(dplyr)
library(lubridate)
library(ggplot2)
---

## 1- Loading and preprocessing the data
# Load the data 
# Process/transform the data (if necessary) into a format suitable for your analysis

---{r}
setwd("~/Ayoub/COURSERA/repro_research")
data <- read.table("./activity.csv",sep=",",header=TRUE)
data$date <- as.Date(data$date)
---

## 2- What is mean total number of steps taken per day?
# Calculate the total number of steps taken per day
# Make a histogram of the total number of steps taken each day
# Calculate and report the mean and median of the total number of steps taken per day

---{r}
sum_steps <- data %>%   filter(!is.na(steps)) %>% group_by(date) %>% summarize(steps = sum(steps)) 
hist(sum_steps$steps, main = "Steps of Each Day", xlab = "Steps by Day")
summary(sum_steps$steps)
mean_steps <- mean(sum_steps$steps)
median_steps <- median(sum_steps$steps)
---

## What is the average daily activity pattern?
# Make a time series plot of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all days (y-axis)
# Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?

---{r}
eachIT = aggregate(data$steps, by=list(interval = data$interval), FUN=mean, na.rm = TRUE)
eachIT$interval <- round(eachIT$interval, 0)       
colnames(eachIT) <- c("interval", "steps")
plot(eachIT, type = "l" )
max_steps = eachIT$interval[which(eachIT$steps == max(eachIT$steps))]
---

## Imputing missing values
# Calculate and report the total number of missing values in the dataset
# Devise a strategy for filling in all of the missing values in the dataset
# Create a new dataset that is equal to the original dataset but with the missing data filled in.
# Make a histogram of the total number of steps taken each day 
#and Calculate and report the mean and median total number of steps taken per day. 

---{r}
sum(is.na(data$steps))
new_data <- data
na_steps <- is.na(new_data$steps)
interV <- tapply(new_data$steps, new_data$interval, mean, na.rm=TRUE, simplify=TRUE)
new_data$steps[na_steps] <- interV[as.character(new_data$interval[na_steps])]
new_sum_steps <- new_data %>%   filter(!is.na(steps)) %>% group_by(date) %>% summarize(steps = sum(steps)) 
hist(new_sum_steps$steps, main = "Steps of each day", xlab = "Steps by day")
summary(new_sum_steps$steps)
new_mean_steps <- mean(new_sum_steps$steps)
new_median_steps <- median(new_sum_steps$steps)
---

## Are there differences in activity patterns between weekdays and weekends?
# Create a new factor variable in the dataset with two levels – “weekday” and “weekend” 
# Make a panel plot containing a time series plot  of the 5-minute interval (x-axis) and 
# the average number of steps taken, averaged across all weekday days or weekend days (y-axis). 

---{r}
new_data$DType <-  ifelse(as.POSIXlt(new_data$date)$wday %in% c(0,6), 'weekend', 'weekday')
new_IT <- new_data %>% group_by(interval, DType) %>% summarise(steps = mean(steps))
s <- ggplot(new_IT, aes(x=interval, y=steps, color = DType)) + geom_line() +facet_wrap(~DType, ncol = 1, nrow=2)
print(s)
---
